version: '2'
services:
  db:
    build: 
      context: mysql
      args:
        UID: ${UID}
        GID: ${GID}
        PHAB_USER: ${PHAB_USER}
        PHAB_PWD: ${PHAB_PWD}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    volumes:
      - ./data/mysql:/var/lib/mysql:z
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf:z
    networks:
      - net
    ports:
      - 3306:3306
  aphlict:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    volumes:
      - ./src:/src:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
      - ./etc/aphlict.json:/etc/aphlict.json:z
    command: ["/usr/local/bin/aphlict"]
    networks:
      - net
    depends_on:
      - db
  php:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    volumes:
      - ./src:/src:z
      - ./data/repo:/var/repo:z
      - ./etc/www.conf:/etc/php7/php-fpm.d/www.conf:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
    networks:
      - net
    depends_on:
      - aphlict
  phd:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
        restart: always
    volumes:
      - ./src:/src:z
      - ./data/repo:/var/repo:z
      - ./etc/www.conf:/etc/php7/php-fpm.d/www.conf:z
      - ./etc/local.json:/src/phabricator/conf/local/local.json:z
    command: ["/usr/local/bin/phd"]
    networks:
      - net
    depends_on:
      - aphlict
  nginx:
    build: nginx
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./src:/src:z
    networks:
      - net
    ports:
      - ${PORT}:8081
    depends_on:
      - php
      - aphlict
networks:
  net:
    external: false
